[pytest]
addopts = ["--strict-markers"]
usefixtures = ["setup_session"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "sample",
    "serial",
    "classy",
    "inClassy",
    "other"
]
